<?php

return [
    'slides' => [
        [
            'eyebrow' => 'یک پلتفرم برای همه نقش‌ها',
            'title' => 'مدیریت ساختمان، ساده‌تر برای همه.',
            'description' => 'شارژ، درخواست خدمات و پیام‌های ساختمان را در بیلدینو پیگیری کنید.',
            'image' => 'images/buildings.webp',
            'image_alt' => 'تصویر مفهومی ساختمان‌های متصل در بیلدینو',
            'target' => '#features',
            'cta' => 'امکانات را ببینید',
        ],
        [
            'eyebrow' => 'شفافیت در امور مالی',
            'title' => 'از شارژ ساختمان تا گزارش مالی، منظم و قابل پیگیری.',
            'description' => 'صورتحساب‌ها، سررسیدها و وضعیت پرداخت را در نمایی یکپارچه دنبال کنید.',
            'image' => 'images/building-with-shadow.webp',
            'image_alt' => 'تصویر مفهومی ساختمان در محیط دیجیتال',
            'target' => '#features',
            'cta' => 'امکانات مالی',
        ],
        [
            'eyebrow' => 'خدمات نزدیک به شما',
            'title' => 'درخواست خدمات ساختمان، بدون پیگیری‌های پراکنده.',
            'description' => 'از تعمیرات و رزرو فضا تا ارتباط با مدیریت، هر درخواست یک مسیر مشخص دارد.',
            'image' => 'images/buildings.webp',
            'image_alt' => 'تصویر مفهومی خدمات مجتمع در بیلدینو',
            'target' => '#services',
            'cta' => 'خدمات را بشناسید',
        ],
    ],
    'features' => [
        ['icon' => 'building', 'title' => 'مدیریت مجتمع و واحدها', 'description' => 'اطلاعات ساختمان، بلوک و واحد در یک نمای مرتب.', 'target' => '#services'],
        ['icon' => 'wallet', 'title' => 'شارژ و امور مالی', 'description' => 'صورتحساب، سررسید و سابقه پرداخت در دسترس.', 'target' => '#services'],
        ['icon' => 'calendar', 'title' => 'رزرو فضاهای مشترک', 'description' => 'مشاهده زمان‌های آزاد و ثبت درخواست رزرو.', 'target' => '#services'],
        ['icon' => 'unit', 'title' => 'تردد و مهمان', 'description' => 'هماهنگی ورود مهمان و امور مرتبط با نگهبانی.', 'target' => '#services'],
        ['icon' => 'bell', 'title' => 'اطلاع‌رسانی', 'description' => 'پیام‌های مدیریت و وضعیت درخواست‌ها در یک جا.', 'target' => '#services'],
        ['icon' => 'tool', 'title' => 'درخواست خدمات', 'description' => 'ثبت و پیگیری تعمیرات و خدمات ساختمان.', 'target' => '#services'],
    ],
    'services' => [
        ['icon' => 'building', 'title' => 'مدیریت ساختمان', 'description' => 'نظم در امور واحدها، نقش‌ها و فعالیت‌های مجتمع.', 'status' => 'راهکار اصلی'],
        ['icon' => 'unit', 'title' => 'تردد و امنیت', 'description' => 'هماهنگی مهمان و ارتباط بهتر با نگهبانی.', 'status' => 'راهکار اصلی'],
        ['icon' => 'wallet', 'title' => 'پرداخت و امور مالی', 'description' => 'مدیریت شارژ، صورتحساب و گزارش‌های مالی.', 'status' => 'راهکار اصلی'],
        ['icon' => 'calendar', 'title' => 'رزرو فضاها', 'description' => 'درخواست استفاده از امکانات مشترک ساختمان.', 'status' => 'راهکار اصلی'],
        ['icon' => 'bell', 'title' => 'ارتباط و اطلاع‌رسانی', 'description' => 'اعلان‌ها، پیام‌ها و پیگیری درخواست‌ها.', 'status' => 'راهکار اصلی'],
        ['icon' => 'tool', 'title' => 'بازارچه خدمات ساختمان', 'description' => 'درخواست خدمات موردنیاز ساختمان از یک جا.', 'status' => 'در برنامه توسعه'],
        ['icon' => 'activity', 'title' => 'خدمات خودرو در محل', 'description' => 'راهکاری برای درخواست خدمات خودرو در مجتمع.', 'status' => 'در برنامه توسعه'],
        ['icon' => 'wallet', 'title' => 'پرداخت اعتباری', 'description' => 'امکان پرداخت هزینه‌ها به‌صورت اعتباری.', 'status' => 'در برنامه توسعه'],
        ['icon' => 'check', 'title' => 'بیمه و خدمات مکمل', 'description' => 'دسترسی به خدمات بیمه و امکانات تکمیلی.', 'status' => 'در برنامه توسعه'],
    ],
    // Temporary sample buildings; replace with actual covered buildings.
    'projects' => [
        ['name' => 'مجتمع آفتاب', 'description' => 'مدیریت شارژ، اطلاع‌رسانی و درخواست خدمات ساختمان.', 'image' => 'images/buildings.webp', 'image_alt' => 'تصویر ساختمان‌های مجتمع آفتاب'],
        ['name' => 'برج نارون', 'description' => 'رزرو امکانات مشترک و هماهنگی ورود مهمان.', 'image' => 'images/building-with-shadow.webp', 'image_alt' => 'تصویر ساختمان برج نارون'],
        ['name' => 'مجتمع سرو', 'description' => 'ارتباط ساکنان با مدیریت و پیگیری امور واحدها.', 'image' => 'images/buildings.webp', 'image_alt' => 'تصویر ساختمان‌های مجتمع سرو'],
    ],
    'statistics' => [],
    'articles' => [],
    'plans' => [
        ['name' => 'ساختمان', 'subtitle' => 'برای مدیریت منظم یک ساختمان', 'items' => ['مدیریت واحدها و نقش‌ها', 'شارژ و صورتحساب', 'اطلاع‌رسانی و درخواست‌ها']],
        ['name' => 'مجتمع', 'subtitle' => 'برای مجموعه‌های چندبخشی', 'items' => ['امکانات پلن ساختمان', 'رزرو فضاهای مشترک', 'فرایندهای متناسب با مجتمع']],
        ['name' => 'سازمانی', 'subtitle' => 'برای برج‌ها و مجموعه‌های بزرگ', 'items' => ['ساختار چندبلوکی', 'سطوح دسترسی متنوع', 'بررسی نیازها و راهکار اختصاصی']],
    ],
    'contact' => [
        'phone' => env('BUILDINO_CONTACT_PHONE', '021-57702'),
        'email' => env('BUILDINO_CONTACT_EMAIL', ''),
        'address' => env('BUILDINO_CONTACT_ADDRESS', 'قائم مقام فراهانی، کوچه آزادگان، پلاک ۲۵، واحد ۲۳-۲۴'),
        'recipient' => env('BUILDINO_CONTACT_EMAIL', ''),
        'phone_is_demo' => false,
        'email_is_demo' => blank(env('BUILDINO_CONTACT_EMAIL')),
        'address_is_demo' => false,
        'whatsapp' => env('BUILDINO_WHATSAPP_NUMBER', ''),
        'instagram' => env('BUILDINO_INSTAGRAM_URL', ''),
        'linkedin' => env('BUILDINO_LINKEDIN_URL', ''),
    ],
];
